<#
.SYNOPSIS
    Commit the current working tree as V2 and tag it.

.DESCRIPTION
    Snapshots everything currently on disk into one commit on the current
    branch, then creates an annotated tag so v2 can be checked out or diffed
    against the v4-baseline commit later.

    .gitignore already excludes the things that must NOT be committed:
        .venv/  __pycache__/  data/chromadb*/  data/*.pkl  app/runtime/
        app/startup_debug.log
    The script re-checks for them anyway and refuses to continue if one is
    staged, because a committed app.db leaks user accounts and chat history.

.EXAMPLE
    .\save_v2.ps1                    # review, confirm, commit, tag
    .\save_v2.ps1 -Force             # no confirmation prompt
    .\save_v2.ps1 -Push              # also push branch + tag to origin
    .\save_v2.ps1 -Message "V2: ..." # custom commit subject
#>

[CmdletBinding()]
param(
    [string] $Message = "V2: tier ladder, auth, queue, sessions, smalltalk gate fix",
    [string] $Tag     = "v2",
    [switch] $Push,
    [switch] $Force
)

# NOT "Stop": git writes ordinary progress to stderr, and Windows PowerShell 5.1
# turns that into a terminating error (git push is the usual victim). Every git
# call below is checked with $LASTEXITCODE instead, which is the reliable signal.
$ErrorActionPreference = "Continue"

function Fail($text) { Write-Host "ERROR: $text" -ForegroundColor Red; exit 1 }
function Info($text) { Write-Host $text -ForegroundColor Cyan }

# -- run from the repository root, wherever the script was invoked from ------
Set-Location -Path $PSScriptRoot
if (-not (Test-Path ".git")) { Fail "No .git here. Run this from the repo root." }

$branch = (git rev-parse --abbrev-ref HEAD).Trim()
Info "Repository : $PSScriptRoot"
Info "Branch     : $branch"

if (-not (git status --porcelain)) { Fail "Nothing to commit - working tree is clean." }

# -- stale lock check --------------------------------------------------------
# git creates .git/index.lock for the duration of an index write and removes it
# afterwards. A leftover EMPTY lock with no git process running means some
# earlier git call was killed (or, in our case, ran against the folder while it
# was mounted read-restricted and could not unlink its own lock). Every later
# 'git add' then fails with a confusing "Another git process seems to be
# running". Detect it and say so plainly instead.
$lock = Join-Path $PSScriptRoot ".git\index.lock"
if (Test-Path $lock) {
    $item    = Get-Item $lock -Force
    $ageMin  = [int]((Get-Date) - $item.LastWriteTime).TotalMinutes
    $running = @(Get-Process -Name git -ErrorAction SilentlyContinue).Count

    Write-Host "Found .git/index.lock  ($($item.Length) bytes, $ageMin min old, $running git process(es) running)" -ForegroundColor Yellow

    if ($running -gt 0) {
        Fail "A git process really is running. Let it finish, then re-run this script."
    }
    if ($item.Length -gt 0) {
        Fail "The lock is non-empty, so a git write may have been interrupted mid-way. Inspect it before deleting: $lock"
    }

    if (-not $Force) {
        $answer = Read-Host "Lock looks stale (empty, no git running). Delete it? [y/N]"
        if ($answer -notmatch '^(y|yes)$') { Fail "Left the lock in place; nothing done." }
    }
    Remove-Item $lock -Force
    Info "Removed stale lock."
}


# -- stage everything that .gitignore allows ---------------------------------
git add -A
if ($LASTEXITCODE -ne 0) { Fail "git add failed." }

$staged = git diff --cached --name-only
if (-not $staged) { Fail "Nothing staged after 'git add -A'." }

# -- refuse to commit secrets, databases or regenerable indexes --------------
$forbidden = @(
    '(^|/)app/runtime/',      # app.db - user accounts, password hashes, chats
    '(^|/)data/chromadb',     # vector index, regenerated by run.ps1 -Ingest
    '\.pkl$',                 # bm25_index.pkl, same
    'startup_debug\.log$',
    '(^|/)\.venv/', '(^|/)venv/', '__pycache__/',
    '\.env$'
)
$bad = $staged | Where-Object { $f = $_; $forbidden | Where-Object { $f -match $_ } }
if ($bad) {
    Write-Host "Refusing to commit - these should stay out of git:" -ForegroundColor Red
    $bad | ForEach-Object { Write-Host "    $_" -ForegroundColor Red }
    Write-Host "Unstage with:  git reset HEAD <path>   (and add it to .gitignore)"
    git reset | Out-Null
    exit 1
}

# -- warn about anything large (models, dumps) -------------------------------
$large = $staged | Where-Object { Test-Path $_ } |
    ForEach-Object { Get-Item $_ } |
    Where-Object { $_.Length -gt 10MB }
if ($large) {
    Write-Host "WARNING: large files staged -" -ForegroundColor Yellow
    $large | ForEach-Object {
        Write-Host ("    {0}  ({1:N1} MB)" -f $_.Name, ($_.Length / 1MB)) -ForegroundColor Yellow
    }
}

# -- show the user exactly what is about to be recorded ----------------------
Info "`nFiles in this commit ($($staged.Count)):"
# --no-pager: without it git pipes the stat through 'less' and the script
# appears to hang on a ':' prompt, waiting for a keypress nobody expects.
git --no-pager diff --cached --stat

if (-not $Force) {
    $answer = Read-Host "`nCommit as '$Tag'? [y/N]"
    if ($answer -notmatch '^(y|yes)$') { git reset | Out-Null; Fail "Aborted; nothing staged." }
}

# -- commit ------------------------------------------------------------------
$body = @"
$Message

Snapshot of the working tree as of V2.

Since the v4 retrieval baseline (353305b):
- Tier ladder A/B/C/D wired end to end (core/tiers.py, core/pipeline.py)
- Rule-based fact check and template rendering for Tier A (no LLM in the path)
- Auth, request queue, conversation sessions and summarisation
- smalltalk gate rewritten: segment matching with typo tolerance, replacing
  set-equality matching that let social messages fall through to retrieval
- context expansion now requires an admin term or a facet word, so a short
  farewell is no longer expanded with the previous procedure title and
  answered at Tier A
- app/test_smalltalk_gate.py: 68 cases, no models, runs in under a second

Retrieval is untouched; R@1 0.8556 still stands and the index needs no rebuild.

Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>
Claude-Session: https://claude.ai/code/session_01Y2VbHt1dzfu1u7YYEA7ErE
"@

$tmp = [System.IO.Path]::GetTempFileName()
[System.IO.File]::WriteAllText($tmp, $body, (New-Object System.Text.UTF8Encoding $false))
git commit --file="$tmp"
$committed = $LASTEXITCODE
Remove-Item $tmp -Force
if ($committed -ne 0) { Fail "git commit failed." }

# -- tag ---------------------------------------------------------------------
if (git tag --list $Tag) {
    Write-Host "Tag '$Tag' already exists - leaving it alone." -ForegroundColor Yellow
} else {
    git tag -a $Tag -m $Message
    Info "Tagged $Tag"
}

# -- push (opt-in) -----------------------------------------------------------
if ($Push) {
    if (-not (git remote)) { Fail "No remote configured; commit is saved locally." }
    git push origin $branch
    git push origin $Tag
    Info "Pushed $branch and $Tag to origin."
}

Info "`nDone."
git --no-pager log --oneline -3
Write-Host "`nCompare against the v4 baseline with:" -ForegroundColor DarkGray
Write-Host "    git diff 353305b..$Tag --stat" -ForegroundColor DarkGray
